### ISSUE TITLE
package.json bin is wrong

### ISSUE THREAD

**Issue by 0x6368656174** [ngneat/until-destroy#108]
Property `bin` in `package.json` must contain bin file name in object key, but `package.json` in until-destroy contains `@ngneat/until-destroy`. It is wrong file name, that why this package can not linking with yarn2:
```
➤ YN0001: │ Error: Invalid filename: "@ngneat/until-destroy"
    at E (/Users/0x6368656174/projects/tomoru/.yarn/releases/yarn-berry.js:31:29721)
    at a (/Users/0x6368656174/projects/tomoru/.yarn/releases/yarn-berry.js:77:172119)
    at a (/Users/0x6368656174/projects/tomoru/.yarn/releases/yarn-berry.js:77:172287)
    at a (/Users/0x6368656174/projects/tomoru/.yarn/releases/yarn-berry.js:77:172287)
    at a (/Users/0x6368656174/projects/tomoru/.yarn/releases/yarn-berry.js:77:172179)
    at r.loadManifest (/Users/0x6368656174/projects/tomoru/.yarn/releases/yarn-berry.js:77:172376)
    at async baseFs (/Users/0x6368656174/projects/tomoru/.yarn/releases/yarn-berry.js:77:171686)
    at async H.finalizeInstallWithPnp (/Users/0x6368656174/projects/tomoru/.yarn/releases/yarn-berry.js:77:168320)
    at async H.finalizeInstall (/Users/0x6368656174/projects/tomoru/.yarn/releases/yarn-berry.js:31:316117)
    at async se.linkEverything (/Users/0x6368656174/projects/tomoru/.yarn/releases/yarn-berry.js:37:192705)
```

Current value:
```
"bin": {
  "@ngneat/until-destroy": "migration/run.js"
 },
```

Key `@ngneat/until-destroy` must be changed to valid file name.

**Comment by NetanelBasal** [comment]
How do you get this error?

**Comment by 0x6368656174** [comment]
This error is displayed when I try install this package by yarn2 with monorepo config. Yarn tries to make link for bin, but can not do it, because `@ngneat/until-destroy` is not valid file name (file name can not contains `/`).

**Comment by NetanelBasal** [comment]
The `bin` property doesn't point to the library; it's only for the migration.

**Comment by NetanelBasal** [comment]
We need to use it so that users will be able to run `npx @ngneat/until-destroy --base my/path`

**Comment by 0x6368656174** [comment]
I anderstand, but Yanr try make links. You can make change package.json like this:
```
  "version": "...",
  "bin": "migration/run.js"
```

See second example in https://docs.npmjs.com/files/package.json#bin.

**Comment by NetanelBasal** [comment]
Cool, do you want to create a PR?

**Comment by 0x6368656174** [comment]
I wanted create but I become too lazy to understand if you Commit Message Guidelines=)

**Comment by NetanelBasal** [comment]
git commit -m "fix(lib): refactor bin property" :)

**Comment by 0x6368656174** [comment]
Ok👍  One moment

**Comment by NetanelBasal** [comment]
And run "npm run contributors:add"

**Comment by 0x6368656174** [comment]
The second comment was too late, I already do PR=)
