### ISSUE TITLE
Jest crash on transforming "export * from './index'"

### ISSUE THREAD

**Issue by jogelin** [ngneat/until-destroy#160]
Hello,

I don't really know what is causing this issue but I am working on upgrading my monorepo from Nx 12 .0.8 to 12.5.5.

Everything works fine...just Jest test related to until destroy are crashing the transformation.

```bash
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    my-project/node_modules/@ngneat/until-destroy/ngneat-until-destroy.d.ts:4
    export * from './index';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      2 | import { fromEvent, Subscription } from 'rxjs';
      3 | import { tap } from 'rxjs/operators';
    > 4 | import { UntilDestroy, untilDestroyed } from '@ngneat/until-destroy';
        | ^
      5 |
      6 | @UntilDestroy()
      7 | @Directive({

      at Runtime.createScriptFromCode (../../../../node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (../../../shared/utils/src/lib/interaction/stop-propagation.directive.ts:4:1)

```

Tests that do not have any links with the until destroy library works fine.

I saw you also migrated to Nx so any ideas ?

**Comment by jogelin** [comment]
I also played with the `angular-preset-jest` and adding https://thymikee.github.io/jest-preset-angular/docs/guides/angular-ivy/ and I get this error also on until-destroy:

 ```bash
 ngcc-jest-processor: running ngcc
Error: Unable to process any formats for the following entry-points (tried es2015, main): 
  - /Users/user/project/node_modules/@ngneat/until-destroy
    at /Users/user/project/node_modules/@angular/compiler-cli/ngcc/src/execution/analyze_entry_points.js:94:23
    at new ClusterMaster (/Users/user/project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:45:30)
    at ClusterExecutor.<anonymous> (/Users/user/project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/executor.js:39:50)
    at step (/Users/user/project/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/user/project/node_modules/tslib/tslib.js:124:57)
    at /Users/user/project/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/user/project/node_modules/tslib/tslib.js:113:16)
    at /Users/user/project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/executor.js:33:91
    at AsyncLocker.<anonymous> (/Users/user/project/node_modules/@angular/compiler-cli/ngcc/src/locking/async_locker.js:57:50)
Error:  NGCC failed .
    at Object.<anonymous> (/Users/user/project/node_modules/jest-preset-angular/build/utils/ngcc-jest-processor.js:36:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/user/project/node_modules/jest-preset-angular/ngcc-jest-processor.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

Process finished with exit code 1
 ```

**Comment by arturovt** [comment]
Hey, thank you for the issue! This was my mistake since I've used the wrong builder before publishing the library.

I've published `@ngneat/until-destroy@8.1.1`, could you give it a try?

**Comment by arturovt** [comment]
I've tried the latest version inside the dedicated Nx workspace and it worked perfectly with Jest 27. I'll close the issue for now, feel free to re-open if you're still facing issues.

**Comment by jogelin** [comment]
Working fine thank you 👍

**Comment by tstackhouse** [comment]
I'm actually seeing this error with until-destroy@9.0.0 and jest@27.0.3 in an nx@12.5.2 environment... Kind of at a loss
