### ISSUE TITLE
Angular 15 Directive Composition API: Cannot access [component] before initialization.

### ISSUE THREAD

**Issue by maximLyakhov** [ngneat/until-destroy#219]
Steps to reproduce:

- create **directive** and use _@UntilDestroy()_
- create **component**
- add **directive** which uses _@UntilDestroy()_ to hostDirectives array in Component decorator
- use **component** somewhere
- get similar error:

```
provider.ts:24 Uncaught ReferenceError: Cannot access 'component' before initialization
    at Module.component (provider.ts:24:2)
    at 84058 (directive.ts:11:31)
    at __webpack_require__ (bootstrap:19:1)
    at 39793 (provider.ts:24:2)
    at __webpack_require__ (bootstrap:19:1)
    at 56546 (token.ts:10:66)
    at __webpack_require__ (bootstrap:19:1)
    at 29142 (main.ts:7:38)
    at __webpack_require__ (bootstrap:19:1)
    at 72513 (main.js:14:70)
```

**Comment by maximLyakhov** [comment]
> Could you please provide a minimal reproducible example?

https://stackblitz.com/edit/angular-ivy-crmpub

It's running normally on stackblitz, but on freshly created project throws mentioned error.

**Comment by arturovt** [comment]
You can create a fresh project, push it to the git and provide a link accordingly.

**Comment by arturovt** [comment]
I'm not able to reproduce it in a newly created app.
